### ISSUE TITLE
[BUG] Failed to initialize tesseract engine.

### ISSUE THREAD

**Issue by GDRMLive** [TinusHeystek/new-world-minimap-release#11]
**Describe the bug**
It runs normal but cant read the coordinates because is not initialize tesseract engine. So it doesn't find me position on mini map.

**Hardware/Software info**
A short description of the following : 
- Resolution 1080p
- Os version Windows 10 20H2
- Minimap Version you are using New.World.Minimap.v0.0.11
**Screenshots**
https://drive.google.com/file/d/1FS_yQuswupkti8NSc5_M0u70lVm7rL9u/view?usp=sharing
**Additional context**
I tried everything i could, i search on https://github.com/charlesw/tesseract/wiki/Error-1 and i try it but could do much because most are crypto. Here some more information i am from Brazil, my pc specs amd ryzen 3060/rtx 2060/16g dd4 ram 3200mhz. I think could be the tessdata folder path i don't know please help T_T

**Comment by ajnart** [comment]
Thanks for the help @Zotikus1001 !
Is this solved ?

**Comment by TinusHeystek** [comment]
Please try the latest version. (v0.12.2)
