### ISSUE TITLE
[SUGGESTION] Hide buttons when minimap is locked.

### ISSUE THREAD

**Issue by Szyler** [TinusHeystek/new-world-minimap-release#12]
**Describe the suggestion**
Can the buttons on the minimap be hidden when the minimap is locked? It just clutters the screen with stuff you can't interact with anyway (as it is locked).

**Screenshots / Art**
https://i.imgur.com/xru6mqe.png

**Why ?**
Removes screen clutter.

**Comment by TinusHeystek** [comment]
Hi Szyler,

Working on that now ;)

**Comment by TinusHeystek** [comment]
Done
