### ISSUE TITLE
Black Screen [BUG]

### ISSUE THREAD

**Issue by Gracen-TT** [TinusHeystek/new-world-minimap-release#18]
**Describe the bug**
I start the application before I start the game, I have also tried it after game is started, and get the mini map and a black screen.

**Hardware/Software info**
A short description of the following : 
using 2 monitors but the main monitor is where the application starts and the game
- 1920 * 1080
- 10
- 0.12.1

![image](https://user-images.githubusercontent.com/3950362/137753642-a464064e-680b-4be5-9bc6-953258f0ee6e.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/3950362/137753729-4d683499-63ee-4d5f-82ef-ab8ebf196c44.png)

**Additional context**
not sure what is going on other than the application is sitting on top of the game but the black screen is blocking out the viewing of the game.

**Comment by TinusHeystek** [comment]
Hi Please have a look at the Discord Server for a possible solution for this issue.

![image](https://user-images.githubusercontent.com/56069078/138230407-71da5b5d-9764-4296-bba3-2a1d3561e6b9.png)
