### ISSUE TITLE
[BUG] No more minimap since today

### ISSUE THREAD

**Issue by Cryshah** [TinusHeystek/new-world-minimap-release#32]
**Describe the bug**
no more minimap.
app launched and running (icon in taskbar), but nothing showed since today, all fine yesterday
tried to restart app, restart game, reboot PC, launch other unity app, ...

**Hardware/Software info**
A short description of the following : 
- Resolution : 5120x1440
- Os version : W11
- Minimap Version you are using : 0.14.0

**Screenshots**

**Additional context**
I had a graphic crash yesterday, no signal on both screens

**Comment by TinusHeystek** [comment]
Hi, seems like an issue that can be resolved by deleting the project folder from the windows Registry. Please have a look on the Discord channel under the #Known-fixes channel.

**Comment by TinusHeystek** [comment]
Hi will add the Discord link to the main page.

https://discord.gg/rVmaJpypkP
