### ISSUE TITLE
[BUG] minimap doesn't see my current position

### ISSUE THREAD

**Issue by bjbeare** [TinusHeystek/new-world-minimap-release#7]
**Describe the bug**
minimap didn't update its position when i 'return to in'

**Hardware/Software info**
A short description of the following : 
windows 10. 4k video. full screen.
0.11

**Screenshots**

**Additional context**
i do have my position and fps showing in the top right of my display.

**Comment by ajnart** [comment]
There's a section called "Releases" made for just that on the main page.

**Comment by bjbeare** [comment]
.12 fixed it. ty
